# Generated by Django 5.1.2 on 2024-10-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dziki_klucz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczby_na_sterydach', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=100)),
                ('liczby', models.IntegerField()),
                ('pole_dziki_klucz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APLIKACJA.dziki_klucz')),
            ],
        ),
    ]
